name: Build with Gradle

on:
  workflow_dispatch:
  push:

env:
  GRADLE_OPTS: '-Dorg.gradle.jvmargs=-Xmx4096M -Dorg.gradle.daemon=false'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout development
      uses: actions/checkout@v2
      with:
        ref: 'development'

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Build
      run: ./gradlew -i --stacktrace lintSnapshotBasicRelease testSnapshotBasicDebugUnitTest assembleSnapshotBasicDebug

    - name: Upload apk
      uses: actions/upload-artifact@v2
      with:
        name: services_app-snapshot-basic-debug.apk
        path: services_app/build/outputs/apk/snapshotBasic/debug/services_app-snapshot-basic-debug.apk
        if-no-files-found: error

    - name: Upload lint results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: lint-results
        path: services_app/build/reports/lint-results-*
        if-no-files-found: error

    - name: Upload test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: services_app/build/reports/tests
        if-no-files-found: error

  connected-test:
    needs: build
    runs-on: macos-10.15

    strategy:
      fail-fast: false
      matrix:
        abi: [default, google_apis]
        api: [21, 22, 23, 24, 25, 26, 27, 28]
        exclude:
        - api: 28
          abi: google_apis

    steps:
    - name: Checkout development
      uses: actions/checkout@v2
      with:
        ref: 'development'

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Run connectedSnapshotBasicDebugAndroidTest
      uses: reactivecircus/android-emulator-runner@v2
      timeout-minutes: 60
      with:
        api-level: ${{ matrix.api }}
        target: ${{ matrix.abi }}
        sdcard-path-or-size: 1024M
        profile: Nexus 7
        emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -memory 2048
        script: |
          adb logcat > logcat.log 2>&1 &
          ./gradlew -i --stacktrace connectedSnapshotBasicDebugAndroidTest

    - name: Upload androidTest results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: androidTest-results-api${{ matrix.api }}-${{ matrix.abi }}
        path: services_app/build/reports/androidTests
        if-no-files-found: error

    - name: Upload emulator logcat
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: logcat.log-api${{ matrix.api }}-${{ matrix.abi }}
        path: logcat.log
        if-no-files-found: error
